# Generated by Django 4.0.5 on 2022-06-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(db_table='actor_movie', to='movie.movie'),
        ),
    ]
