# Generated by Django 4.0.5 on 2022-06-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_actor_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(db_table='actor_movie', related_name='tags', to='movie.movie'),
        ),
    ]
